<#
.SYNOPSIS
    Verify Exoskeleton Claude Code project installation.

.DESCRIPTION
    Checks project-level .claude assets generated by install-claude.ps1.
    This verifier is read-only and exits with code 0 when required files are
    present and parseable, otherwise exits with code 1.

.PARAMETER ProjectRoot
    Target business project root. Defaults to current directory.

.PARAMETER Quiet
    If set, prints only the final status.
#>
[CmdletBinding()]
param(
    [string]$ProjectRoot = (Get-Location).Path,
    [switch]$Quiet
)

$ErrorActionPreference = "Stop"
$failed = 0
$warned = 0

function Write-Ok([string]$msg) {
    if (-not $Quiet) { Write-Host ("  [OK]   " + $msg) -ForegroundColor Green }
}

function Write-WarnMsg([string]$msg) {
    $script:warned++
    if (-not $Quiet) { Write-Host ("  [WARN] " + $msg) -ForegroundColor Yellow }
}

function Write-Fail([string]$msg) {
    $script:failed++
    if (-not $Quiet) { Write-Host ("  [FAIL] " + $msg) -ForegroundColor Red }
}

function Resolve-FullPath([string]$Path) {
    return $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($Path)
}

function Check-Path([string]$RelativePath, [string]$Label) {
    $fullPath = Join-Path $ProjectRoot $RelativePath
    if (Test-Path $fullPath) {
        Write-Ok ($Label + ": " + $RelativePath)
    } else {
        Write-Fail ($Label + " missing: " + $RelativePath)
    }
}

function Check-MinFiles([string]$RelativePath, [string]$Pattern, [int]$MinCount, [string]$Label) {
    $fullPath = Join-Path $ProjectRoot $RelativePath
    if (-not (Test-Path $fullPath -PathType Container)) {
        Write-Fail ($Label + " directory missing: " + $RelativePath)
        return
    }

    $items = Get-ChildItem -Path $fullPath -Filter $Pattern -Recurse -File -ErrorAction SilentlyContinue
    if ($items.Count -lt $MinCount) {
        Write-Fail ("$Label expected at least $MinCount $Pattern file(s), found $($items.Count)")
    } else {
        Write-Ok ("$Label count: $($items.Count)")
    }
}

$ProjectRoot = Resolve-FullPath -Path $ProjectRoot

if (-not $Quiet) {
    Write-Host "Exoskeleton Claude Code installation verification" -ForegroundColor Cyan
    Write-Host "Project root: $ProjectRoot"
    Write-Host ""
}

if (-not (Test-Path $ProjectRoot -PathType Container)) {
    Write-Fail ("Project root missing: " + $ProjectRoot)
    Write-Host "Verification failed: project root not found." -ForegroundColor Red
    exit 1
}

Check-Path ".claude" "Directory"
Check-Path ".claude\settings.json" "File"
Check-Path ".claude\commands" "Directory"
Check-Path ".claude\agents" "Directory"
Check-Path ".claude\skills" "Directory"
Check-Path ".claude\hooks" "Directory"
Check-Path ".claude\hooks\common.ps1" "File"
Check-Path ".claude\hooks\harness-report.ps1" "File"
Check-Path ".claude\hooks\claude-pre-tool-use.ps1" "File"
Check-Path ".claude\hooks\claude-user-prompt-submit.ps1" "File"
Check-Path ".claude\hooks\claude-post-tool-use.ps1" "File"
Check-Path ".claude\exoskeleton-skill-index.md" "File"
Check-Path ".claude\tool-call-budget.md" "File"
Check-Path "CLAUDE.md" "File"

$settingsPath = Join-Path $ProjectRoot ".claude\settings.json"
if (Test-Path $settingsPath -PathType Leaf) {
    try {
        $raw = Get-Content -Path $settingsPath -Raw -Encoding UTF8
        $null = $raw | ConvertFrom-Json
        Write-Ok ".claude\settings.json is valid JSON"
    } catch {
        Write-Fail ".claude\settings.json exists but is not valid JSON"
    }
}

Check-MinFiles ".claude\commands" "*.md" 7 "Commands"
Check-MinFiles ".claude\agents" "*.md" 10 "Agents"
Check-MinFiles ".claude\skills" "SKILL.md" 1 "Skills"

if (Test-Path (Join-Path $ProjectRoot "AGENTS.md") -PathType Leaf) {
    Write-Ok "AGENTS.md present"
} else {
    Write-WarnMsg "AGENTS.md not found. Run /init before executing governed project workflows."
}

Write-Host ""
if ($failed -eq 0) {
    if (-not $Quiet) {
        if ($warned -gt 0) {
            Write-Host ("Verification passed with " + $warned + " warning(s).") -ForegroundColor Yellow
        } else {
            Write-Host "Verification passed: Claude Code assets are present." -ForegroundColor Green
        }
    }
    exit 0
}

Write-Host ("Verification failed: " + $failed + " check(s) failed, " + $warned + " warning(s).") -ForegroundColor Red
exit 1
