<#
.SYNOPSIS
    Verify Exoskeleton Codex project installation.

.DESCRIPTION
    Checks repo-scoped skills, references, custom agents, approval rules,
    project hooks, and repo-local plugin marketplace assets generated by
    install-codex.ps1.

.PARAMETER ProjectRoot
    Target business project root. Defaults to current directory.

.PARAMETER Quiet
    If set, prints only the final status.
#>
[CmdletBinding()]
param(
    [string]$ProjectRoot = (Get-Location).Path,
    [switch]$Quiet
)

$ErrorActionPreference = "Stop"
$failed = 0
$warned = 0

function Write-Ok([string]$msg) {
    if (-not $Quiet) { Write-Host ("  [OK]   " + $msg) -ForegroundColor Green }
}

function Write-WarnMsg([string]$msg) {
    $script:warned++
    if (-not $Quiet) { Write-Host ("  [WARN] " + $msg) -ForegroundColor Yellow }
}

function Write-Fail([string]$msg) {
    $script:failed++
    if (-not $Quiet) { Write-Host ("  [FAIL] " + $msg) -ForegroundColor Red }
}

function Resolve-FullPath([string]$Path) {
    return $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($Path)
}

function Check-Path([string]$RelativePath, [string]$Label) {
    $fullPath = Join-Path $ProjectRoot $RelativePath
    if (Test-Path $fullPath) {
        Write-Ok ($Label + ": " + $RelativePath)
    } else {
        Write-Fail ($Label + " missing: " + $RelativePath)
    }
}

function Check-MinFiles([string]$RelativePath, [string]$Pattern, [int]$MinCount, [string]$Label) {
    $fullPath = Join-Path $ProjectRoot $RelativePath
    if (-not (Test-Path $fullPath -PathType Container)) {
        Write-Fail ($Label + " directory missing: " + $RelativePath)
        return
    }

    $items = Get-ChildItem -Path $fullPath -Filter $Pattern -Recurse -File -ErrorAction SilentlyContinue
    if ($items.Count -lt $MinCount) {
        Write-Fail ("$Label expected at least $MinCount $Pattern file(s), found $($items.Count)")
    } else {
        Write-Ok ("$Label count: $($items.Count)")
    }
}

function Check-Json([string]$RelativePath, [string]$Label) {
    $fullPath = Join-Path $ProjectRoot $RelativePath
    if (-not (Test-Path $fullPath -PathType Leaf)) {
        Write-Fail "$Label missing: $RelativePath"
        return
    }
    try {
        $raw = Get-Content -Path $fullPath -Raw -Encoding UTF8
        $null = $raw | ConvertFrom-Json
        Write-Ok "$Label is valid JSON"
    } catch {
        Write-Fail "$Label exists but is not valid JSON"
    }
}

$ProjectRoot = Resolve-FullPath -Path $ProjectRoot

if (-not $Quiet) {
    Write-Host "Exoskeleton Codex installation verification" -ForegroundColor Cyan
    Write-Host "Project root: $ProjectRoot"
    Write-Host ""
}

if (-not (Test-Path $ProjectRoot -PathType Container)) {
    Write-Fail ("Project root missing: " + $ProjectRoot)
    Write-Host "Verification failed: project root not found." -ForegroundColor Red
    exit 1
}

Check-Path ".agents\skills" "Directory"
Check-MinFiles ".agents\skills" "SKILL.md" 8 "Repo skills"
Check-MinFiles ".agents\references\commands" "*.md" 7 "Repo workflow references"
Check-MinFiles ".agents\references\rules" "*.mdc" 7 "Repo rule references"
Check-MinFiles ".agents\references\agents" "*.md" 7 "Repo agent references"
Check-MinFiles ".codex\agents" "*.toml" 7 "Codex custom agents"
Check-MinFiles ".codex\rules" "*.rules" 1 "Codex approval rules"
Check-Path ".codex\hooks" "Directory"
Check-Path ".codex\hooks\common.ps1" "File"
Check-Path ".codex\hooks\harness-report.ps1" "File"
Check-Path ".codex\hooks\codex-pre-tool-use.ps1" "File"
Check-Path ".codex\hooks\codex-permission-request.ps1" "File"
Check-Path ".codex\hooks\codex-user-prompt-submit.ps1" "File"
Check-Path ".codex\hooks\codex-pre-compact.ps1" "File"
Check-Path ".codex\hooks\codex-post-compact.ps1" "File"
Check-Path ".codex\hooks\codex-post-tool-use.ps1" "File"
Check-Json ".codex\hooks.json" ".codex hooks.json"
Check-Json ".agents\plugins\marketplace.json" "repo marketplace"
Check-Json "plugins\coding-exoskeleton\.codex-plugin\plugin.json" "plugin manifest"
Check-MinFiles "plugins\coding-exoskeleton\skills" "SKILL.md" 8 "Plugin skills"
Check-MinFiles "plugins\coding-exoskeleton\references\commands" "*.md" 7 "Workflow references"
Check-MinFiles "plugins\coding-exoskeleton\references\rules" "*.mdc" 7 "Rule references"
Check-MinFiles "plugins\coding-exoskeleton\references\agents" "*.md" 7 "Agent references"

if (Test-Path (Join-Path $ProjectRoot "AGENTS.md") -PathType Leaf) {
    Write-Ok "AGENTS.md present"
} else {
    Write-WarnMsg "AGENTS.md not found. Run exoskeleton-init before governed workflows."
}

Write-Host ""
if ($failed -eq 0) {
    if (-not $Quiet) {
        if ($warned -gt 0) {
            Write-Host ("Verification passed with " + $warned + " warning(s).") -ForegroundColor Yellow
        } else {
            Write-Host "Verification passed: Codex assets are present." -ForegroundColor Green
        }
    }
    exit 0
}

Write-Host ("Verification failed: " + $failed + " check(s) failed, " + $warned + " warning(s).") -ForegroundColor Red
exit 1
